# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 499811456c103d111838dbd27f81f7825414733724f73e2525c3244586a94864e18d5e58c21c2f83048a09fec597301fb27912ce55421c7db18b31c84b9ffc36

test:
  secret_key_base: c3c59abffd1568dd229d063c9d91f5d1d7f3985d8089ed553d4f0d25fe716b1522356cdf5ada1c83490106890857de7c472d7fccf2f6711134f77e4f5a8ed089

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
